baseURL = 'https://jonathasborges1.github.io/tenor/'
languageCode = "pt-br"
title = 'Tenor'
# Theme
theme = 'loveit'

# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
#googleAnalytics = "UA-143083330-1"

[params]
title = "Tenor - Blog do Jonathas Borges"
date = "2022-05-05"
description = "A Tenor é uma unidade de conteudo"
images = ["/images/social-share.jpg"]
email = "borgesux@gmail.com"
keywords = "event, google, programming, developers, web, cloud"
copyright = "Tenor Meetup"
cfpUrl = "https://forms.gle/YhqM93oHFXDLn2K48"
subscriptionUrl = "http://meetup.com/gopherio"
appleTouchIcon = "/apple-touch-icon.png"
favicon32 = "/favicon-32x32.png"
favicon16 = "/favicon-16x16.png"
manifest = "/manifest.json"
safariPinnedTab = "/safari-pinned-tab.svg"
themeColor = "#673ab7"

[params.logos]
jumbo = "/images/logos/devfest_color_text.png"
header = "/images/logos/devfest_color_text.png"
footer = "/images/logos/devfest_gray_text.png"

[menu]
[[menu.main]]
identifier = "meetup"
name = "Meetup"
url = "http://meetup.com/gopherio"
weight = 200
external = true